p2Server:Server.java
	javac -cp components.jar Server.java
	java -cp .:./components.jar Server
	
p2Client:clientWindow.java
	javac -cp components.jar clientWindow.java
	java -cp .:./components.jar clientWindow

client:
	java -cp .:./components.jar clientWindow